module.exports = [
  {
    userEmail: "john@example.com",
    orderItems: [
      {
        name: "Apple",
        qty: 2,
        price: 150,
        image: "https://assets.clevelandclinic.org/transform/cd71f4bd-81d4-45d8-a450-74df78e4477a/Apples-184940975-770x533-1_jpg",
      },
      {
        name: "Carrot",
        qty: 5,
        price: 60,
        image: "https://via.placeholder.com/100?text=Carrot",
      },
    ],
    shippingAddress: {
      address: "123 Street",
      city: "Karachi",
      postalCode: "75300",
      country: "Pakistan",
    },
    paymentMethod: "Cash on Delivery",
    itemsPrice: 630,
    taxPrice: 0,
    shippingPrice: 50,
    totalPrice: 680,
    isPaid: false,
    isDelivered: false,
    createdAt: new Date(),
  },
  {
    userEmail: "jane@example.com",
    orderItems: [
      {
        name: "Banana",
        qty: 10,
        price: 80,
        image: "https://via.placeholder.com/100?text=Banana",
      },
    ],
    shippingAddress: {
      address: "456 Avenue",
      city: "Lahore",
      postalCode: "54000",
      country: "Pakistan",
    },
    paymentMethod: "Credit Card",
    itemsPrice: 800,
    taxPrice: 0,
    shippingPrice: 60,
    totalPrice: 860,
    isPaid: true,
    isDelivered: false,
    createdAt: new Date(),
  },
  {
    userEmail: "ali@example.com",
    orderItems: [
      {
        name: "Orange",
        qty: 3,
        price: 120,
        image: "https://via.placeholder.com/100?text=Orange",
      },
      {
        name: "Potato",
        qty: 8,
        price: 40,
        image: "https://via.placeholder.com/100?text=Potato",
      },
    ],
    shippingAddress: {
      address: "789 Road",
      city: "Islamabad",
      postalCode: "44000",
      country: "Pakistan",
    },
    paymentMethod: "Credit Card",
    itemsPrice: 560,
    taxPrice: 0,
    shippingPrice: 30,
    totalPrice: 590,
    isPaid: true,
    isDelivered: true,
    createdAt: new Date(),
  },
  {
    userEmail: "fatima@example.com",
    orderItems: [
      {
        name: "Tomato",
        qty: 6,
        price: 70,
        image: "https://via.placeholder.com/100?text=Tomato",
      },
      {
        name: "Cucumber",
        qty: 4,
        price: 50,
        image: "https://via.placeholder.com/100?text=Cucumber",
      },
    ],
    shippingAddress: {
      address: "101 Blvd",
      city: "Peshawar",
      postalCode: "25000",
      country: "Pakistan",
    },
    paymentMethod: "Cash on Delivery",
    itemsPrice: 420,
    taxPrice: 0,
    shippingPrice: 40,
    totalPrice: 460,
    isPaid: false,
    isDelivered: false,
    createdAt: new Date(),
  },
  {
    userEmail: "ahmed@example.com",
    orderItems: [
      {
        name: "Apple",
        qty: 1,
        price: 150,
        image: "https://assets.clevelandclinic.org/transform/cd71f4bd-81d4-45d8-a450-74df78e4477a/Apples-184940975-770x533-1_jpg",
      },
    ],
    shippingAddress: {
      address: "202 Lane",
      city: "Quetta",
      postalCode: "87300",
      country: "Pakistan",
    },
    paymentMethod: "Credit Card",
    itemsPrice: 150,
    taxPrice: 0,
    shippingPrice: 30,
    totalPrice: 180,
    isPaid: true,
    isDelivered: false,
    createdAt: new Date(),
  },
  {
    userEmail: "sara@example.com",
    orderItems: [
      {
        name: "Carrot",
        qty: 10,
        price: 60,
        image: "https://via.placeholder.com/100?text=Carrot",
      },
      {
        name: "Banana",
        qty: 5,
        price: 80,
        image: "https://via.placeholder.com/100?text=Banana",
      },
    ],
    shippingAddress: {
      address: "303 Street",
      city: "Faisalabad",
      postalCode: "38000",
      country: "Pakistan",
    },
    paymentMethod: "Cash on Delivery",
    itemsPrice: 700,
    taxPrice: 0,
    shippingPrice: 40,
    totalPrice: 740,
    isPaid: false,
    isDelivered: false,
    createdAt: new Date(),
  },
  {
    userEmail: "bilal@example.com",
    orderItems: [
      {
        name: "Potato",
        qty: 20,
        price: 40,
        image: "https://via.placeholder.com/100?text=Potato",
      },
    ],
    shippingAddress: {
      address: "404 Avenue",
      city: "Multan",
      postalCode: "60000",
      country: "Pakistan",
    },
    paymentMethod: "Credit Card",
    itemsPrice: 800,
    taxPrice: 0,
    shippingPrice: 50,
    totalPrice: 850,
    isPaid: true,
    isDelivered: true,
    createdAt: new Date(),
  },
  {
    userEmail: "nadeem@example.com",
    orderItems: [
      {
        name: "Tomato",
        qty: 8,
        price: 70,
        image: "https://via.placeholder.com/100?text=Tomato",
      },
      {
        name: "Orange",
        qty: 6,
        price: 120,
        image: "https://via.placeholder.com/100?text=Orange",
      },
    ],
    shippingAddress: {
      address: "505 Road",
      city: "Sialkot",
      postalCode: "51310",
      country: "Pakistan",
    },
    paymentMethod: "Cash on Delivery",
    itemsPrice: 920,
    taxPrice: 0,
    shippingPrice: 60,
    totalPrice: 980,
    isPaid: false,
    isDelivered: false,
    createdAt: new Date(),
  },
  {
    userEmail: "rabia@example.com",
    orderItems: [
      {
        name: "Cucumber",
        qty: 12,
        price: 50,
        image: "https://via.placeholder.com/100?text=Cucumber",
      },
    ],
    shippingAddress: {
      address: "606 Lane",
      city: "Hyderabad",
      postalCode: "71000",
      country: "Pakistan",
    },
    paymentMethod: "Credit Card",
    itemsPrice: 600,
    taxPrice: 0,
    shippingPrice: 30,
    totalPrice: 630,
    isPaid: true,
    isDelivered: false,
    createdAt: new Date(),
  },
  {
    userEmail: "umar@example.com",
    orderItems: [
      {
        name: "Banana",
        qty: 7,
        price: 80,
        image: "https://via.placeholder.com/100?text=Banana",
      },
      {
        name: "Apple",
        qty: 3,
        price: 150,
        image: "https://assets.clevelandclinic.org/transform/cd71f4bd-81d4-45d8-a450-74df78e4477a/Apples-184940975-770x533-1_jpg",
      },
    ],
    shippingAddress: {
      address: "707 Street",
      city: "Rawalpindi",
      postalCode: "46000",
      country: "Pakistan",
    },
    paymentMethod: "Cash on Delivery",
    itemsPrice: 810,
    taxPrice: 0,
    shippingPrice: 50,
    totalPrice: 860,
    isPaid: false,
    isDelivered: false,
    createdAt: new Date(),
  },
];
